name: CI - Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 2001050926
          MYSQL_DATABASE: health_check_db
          MYSQL_USER: root
          MYSQL_PASSWORD: 2001050926
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Build and Run All Tests Except the Failure One
      - name: Build and Run Success Test
        run: |
          mvn clean test -Dtest=HealthCheckApplicationTests#testHealthCheckSuccess

      # Stop MySQL Service to Simulate Failure
      - name: Stop MySQL (Simulate Failure)
        run: |
          sudo systemctl stop mysql || docker stop $(docker ps -q --filter ancestor=mysql:8.0) || true

      # Run Failure Test to Get 503
      - name: Run Failure Test
        run: |
          mvn test -Dtest=HealthCheckApplicationTests#testHealthCheckFailure
